-- Full BigQuery extraction strategy for T2.3.
--
-- Runtime parameters:
--   @start_date DATE
--   @end_date DATE
--
-- Runtime table:
--   `project.dataset.labeled_addresses`
--     address STRING -- lower-case Ethereum address from entity dictionary

-- transactions.csv
WITH labeled_addresses AS (
  SELECT LOWER(address) AS address
  FROM `project.dataset.labeled_addresses`
),
selected_transactions AS (
  SELECT
    `hash`, from_address, to_address, value, gas, gas_price,
    block_number, block_timestamp, transaction_type, receipt_status,
    CASE
      WHEN LOWER(from_address) IN (SELECT address FROM labeled_addresses)
        OR LOWER(to_address) IN (SELECT address FROM labeled_addresses)
      THEN 'tier1'
      ELSE 'tier2'
    END AS tier
  FROM `bigquery-public-data.crypto_ethereum.transactions`
  WHERE DATE(block_timestamp) BETWEEN @start_date AND @end_date
    AND (
      LOWER(from_address) IN (SELECT address FROM labeled_addresses)
      OR LOWER(to_address) IN (SELECT address FROM labeled_addresses)
      OR MOD(ABS(FARM_FINGERPRINT(`hash`)), 100) = 0
    )
)
SELECT
  `hash`, from_address, to_address, value, gas, gas_price,
  block_number, block_timestamp, transaction_type, receipt_status, tier
FROM selected_transactions;

-- blocks.csv, token_transfers.csv, and contracts.csv are generated by
-- src/nl2sparql/kg/extraction/full_extract.py from the same selected
-- transaction window and dictionary table.
